name: Lightstep Snapshot

on: deployment_status

jobs:
  snapshot:
    runs-on: ubuntu-latest
    name: Attach Snapshot to Repository
    if: github.event.deployment_status.state == 'success'

    steps:
      - name: ğŸ›ï¸ Checkout
        if: success()
        uses: actions/checkout@v2

      - name: ğŸ“¸ Take Lightstep Snapshot 
        id: lightstep-snapshot
        uses: lightstep/lightstep-action-snapshot@master
        with:
          lightstep_api_key: ${{ secrets.LIGHTSTEP_API_TOKEN }}
          lightstep_organization: LightStep
          lightstep_project: demo
          lightstep_snapshot_query: '"service.version" IN ("${{ github.event.deployment.sha }}")'

      - name: ğŸ· Create new tag 
        if: success()
        uses: simpleactions/create-tag@v1.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.deployment.sha }}
          tag: lightstep.snapshot.${{ steps.lightstep-snapshot.outputs.lightstep_snapshot_id }}
          message: ${{ steps.lightstep-snapshot.outputs.lightstep_snapshot_id }}
